#!/usr/bin/expect -f

source lib/common_init.tcl

spawn [lindex $argv 0] data/aislesofennui.dat

expect "Welcome to the Aisles of Ennui"
expect "Coffee Shop"
expect ">"
send "look\r"
expect "A trendy coffee shop.  A shaggy-haired hipster strums dejectedly on a tiny stage."
expect "Exit to the north"
expect ">"
send "west\r"
expect "There is no exit to the west"
expect ">"
send "north\r"
expect "Bohemian District"
expect ">"
send "look\r"
expect "A cobbled street lined with bars and quirky boutiques."
expect "Exit to the south"
expect ">"
