#!/usr/bin/env expect -f

source lib/common_init.tcl

spawn [lindex $argv 0] data/mazesofmayhem.dat

expect "Welcome to the Mazes of Mayhem"
expect "Stone Chamber"
expect "> "
send "look\r"
expect "A chamber of stone, cold and dank"
expect "Exits to the north, south and west"
expect "> "
send "west\r"
expect "Cellar"
expect "> "
send "look\r"
expect "This room appears to be a root cellar"
expect "Exit to the east"
send "exit"
exit
